npmRegistries:
  //pkgs.dev.azure.com/it-casado/yarn-bugs/_packaging/yarn-bugs/npm/registry:
    npmAlwaysAuth: true
    npmAuthIdent: eWFybi1idWdzQGl0LWNhc2Fkby5kZTphYnh3ZmVnNHl5ZmxjbnhraGQydDVibnN1bXdtZzczamF6bXN4eXNwY2o1eGJxZGE2ZjJx

# npmScopes:
#   casado:
#     npmPublishRegistry: "https://pkgs.dev.azure.com/it-casado/yarn-bugs/_packaging/yarn-bugs/npm/registry"
#     npmRegistryServer: "https://pkgs.dev.azure.com/it-casado/yarn-bugs/_packaging/yarn-bugs/npm/registry"
#     npmAlwaysAuth: true
#     npmAuthIdent: "eWFybi1idWdzQGl0LWNhc2Fkby5kZTphYnh3ZmVnNHl5ZmxjbnhraGQydDVibnN1bXdtZzczamF6bXN4eXNwY2o1eGJxZGE2ZjJx"

npmRegistryServer: "https://pkgs.dev.azure.com/it-casado/yarn-bugs/_packaging/yarn-bugs/npm/registry"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
